### ISSUE TITLE
BS + NMS: Patchlist.txt, switches.txt, netlist.txt

### ISSUE THREAD

**Issue by tingvold** [gathering/tgmanage#57]
Gå bort fra tekstfiler. Få så mye av adresseplanen inn i NMS-et som praktisk er mulig, slik at ting bare trenger å legges inn én plass. Ta en diskusjon på hvordan dette best løses.

**Comment by jallakim** [comment]
netlist.txt er den som er «verst» å få implementert i NMS (siden den er ganske stand-alone/ad-hoc).
