### ISSUE TITLE
PXE IPv6 support

### ISSUE THREAD

**Issue by norrs** [gathering/tgmanage#7]
https://wiki.kubuntu.org/UEFI/SecureBoot-PXE-IPv6

**Comment by jallakim** [comment]
Fungerer delvis. PXE bootet via v4, mens under Debian-installasjon ved nettverkstest, så gjør den DHCP6-config hvor man da får ny location for TFTP-lolz. Dette ser ut til å brekke installasjonen, eller at least gjøre Debian confused.

**Comment by KristianLyng** [comment]
This issue was moved to tech-server/tgnms#21

**Comment by KristianLyng** [comment]
Ops, lukket by accident.
